title: Double Double Stats and Trouble
description: Grassroots cricket reports from Two Bats or Not Two Bats. DIY analytics, annotated gaps, and markdown storytelling. By mama
theme: minima
# Optional: Exclude files/folders from the site
exclude:
  - README.md
  - .github/